<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="StateTop" Id="{47de2e36-77f3-40e1-8166-734388e1c343}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION StateTop : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="StateTop">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>