<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="haveDifferentIDs" Id="{1e2a1f0a-e6df-4059-9106-13397bceb00c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION haveDifferentIDs : BOOL
VAR_INPUT
	first: IncomingMessage;
	second: IncomingMessage;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[haveDifferentIDs := (first.id.dtime <> second.id.dtime)
	OR (first.id.lowUUID <> second.id.lowUUID)
	OR (first.id.highUUID <> second.id.highUUID)
    OR (first.id.sequence <> second.id.sequence);]]></ST>
    </Implementation>
    <LineIds Name="haveDifferentIDs">
      <LineId Id="7" Count="0" />
      <LineId Id="10" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>