<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="newMessage" Id="{1e2a1f0a-e6df-4059-9106-13397bceb00c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION newMessage : BOOL
VAR_INPUT
	first: IncomingMessage;
	second: IncomingMessage;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[newMessage := (first.id.dtime <> second.id.dtime)
	OR (first.id.ipv4 <> second.id.ipv4)
	OR (first.id.pid <> second.id.pid)
    OR (first.id.sequence <> second.id.sequence);]]></ST>
    </Implementation>
    <LineIds Name="newMessage">
      <LineId Id="7" Count="0" />
      <LineId Id="10" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>