<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="F_DcToExt" Id="{87a0d92f-e837-404c-80d3-8113dc33c225}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_DcToExt : T_DCTIME64  // Converts a DC time to a TAI-like absolute time expressed in T_DCTIME64 format.
VAR_INPUT
	dcTime: T_DCTIME64;  // 64-bit DC time.
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_DcToExt := F_ConvTcTimeToExtTime64(
	dcTime,
	LINT_TO_ULINT(GVL.DcToTcTimeOffset),
	LINT_TO_ULINT(GVL.DcToExtTimeOffset)
);
]]></ST>
    </Implementation>
    <LineIds Name="F_DcToExt">
      <LineId Id="3" Count="0" />
      <LineId Id="10" Count="3" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>