<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="F_HaveDifferentIDs" Id="{efee81a6-e141-448b-8c77-517e06ad4102}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_HaveDifferentIDs : BOOL
VAR_INPUT
    msg1: ST_MsgToPLC;
    msg2: ST_MsgToPLC;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* First compare the fields most likely to have changed. *)
F_HaveDifferentIDs :=
    (msg1.dtime 	<> msg2.dtime) OR_ELSE
    (msg1.sequence 	<> msg2.sequence) OR_ELSE
    (msg1.lowUUID 	<> msg2.lowUUID) OR_ELSE
    (msg1.highUUID	<> msg2.highUUID);]]></ST>
    </Implementation>
    <LineIds Name="F_HaveDifferentIDs">
      <LineId Id="11" Count="4" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>