<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="StateEnabled" Id="{37de7ef5-3890-457b-b3b9-3d3f0accca78}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION StateEnabled : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="StateEnabled">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>